name: Publish Release

on:
  push:
    tags:
        "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/
          key: ${{ runner.os }}-pio

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

    #   - name: Extract build version
    #     id: get_version
    #     uses: battila7/get-version-action@v2

      - name: Run PlatformIO
        # env:
        #   VERSION: ${{ steps.get_version.outputs.version-without-v }}
        run: pio run

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .pio/build/**/*_merged.bin

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            .pio/build/**/*_merged.bin
          draft: true

        
